### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by SerafimArts** [LaravelRUS/GitterBot#53]
- [ ] Impove achievements
  - [x] Moving achievements from `Core` to `Domains\Bot`
  - [x] Add unque id to achievements (class name currently)
- [x] Remove all deprecated http api (`Interfaces\Gitter`) and move to `serafim/gitter-api` package
  - [x] Refactor streaming API
- [x] Remove old models (`Domains\*`) or move\rewrite them
  - [x] Users
  - [x] Messages
  - [x] Rooms
  - [x] Achievemtns
  - [x] Karma
- [x] Improve Messages API
  - [x] Add messages event bus
  - [x] Add messages question\answer context api
- [ ] Customise rooms options
  - [ ] Add language selection for rooms
  - [x] Add middleware selection
- [x] Middlewares
  - [x] Automatically paste code in pastebin.org or gist.github.com for `LongMessageMiddleware`
  - [ ] Add comment with message which was copied to gist https://github.com/LaravelRUS/GitterBot/issues/55
- [ ] Achievemens
  - [ ] Add additional karmas after achievement receiving
  - [ ] Add behaviors for achievements
    - [ ] Forever
    - [ ] Changeable
    - [ ] Special
  - [ ] Move achievements to middlewares
  - [ ] Add activeity achieve: https://github.com/LaravelRUS/GitterBot/issues/54
  - [ ] Add unique thanks achieve: https://github.com/LaravelRUS/GitterBot/issues/38
  - [ ] Add ahivements page: https://github.com/LaravelRUS/GitterBot/issues/20

**Comment by SerafimArts** [comment]
> Add messages question\answer context api

https://github.com/LaravelRUS/GitterBot/blob/c1ce98a94ce1921853891cfdbadbed241435e073/app/Domains/Analyser/MessageRelations.php

**Comment by SerafimArts** [comment]
> Moving achievements from Core to Domains\Bot

and

> Add unque id to achievements (class name currently)

Commit: https://github.com/LaravelRUS/GitterBot/commit/b3e799e950d44399047c31d7e80a70a0eeadf77e
